FROM python:3.13.11-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

WORKDIR /code
ENV PATH="/code/.venv/bin:$PATH"

COPY .python-version pyproject.toml uv.lock  ./
RUN uv sync --locked 

RUN pip install pandas pyarrow

COPY pipeline.py .

#ENTRYPOINT ["uv","run","python","pipeline.py"]
ENTRYPOINT [ "python", "pipeline.py" ]